-- ewc_xsscythe_localization.lua

local mod = get_mod("extended_weapon_customization_xsscythe")

return {
	mod_name = {
		en = "Extended Weapon Customization - xsScythe",
		ru = "Расширенная настройка оружия - Косы",
		fr = "Personnalisation d'armes étendue - xsScythe",
		["zh-tw"] = "擴展武器自定義 - xsScythe",
		["zh-cn"] = "扩展武器自定义 - xsScythe",
		de = "Erweiterte Waffenanpassung - xsScythe",
		it = "Personalizzazione armi estesa - xsScythe",
		ja = "拡張武器カスタマイズ - xsScythe",
		ko = "확장 무기 커스터마이즈 - xsScythe",
		pl = "Rozszerzona personalizacja broni - xsScythe",
		["pt-br"] = "Personalização de armas estendida - xsScythe",
		es = "Personalización de armas extendida - xsScythe",
	},
	mod_description = {
		en = "Adds several types of melee blades to your weapon customizations, transforming staves into scythes. Let the harvest begin!",
		ru = "Extended Weapon Customization - xsScythe - Добавляет в настройки оружия несколько видов клинков ближнего боя, превращая посохи в косы. Да начнётся жатва!",
		fr = "Ajoute plusieurs types de lames de mêlée à vos personnalisations d'armes, transformant les bâtons en faux. Que la moisson commence !",
		["zh-tw"] = "在武器自定義中添加多種近戰刀刃，將法杖變成鐮刀。收割開始！",
		["zh-cn"] = "在武器自定义中添加多种近战刀刃，将法杖变成镰刀。收割开始！",
		de = "Fügt Ihren Waffenanpassungen verschiedene Arten von Nahkampfklingen hinzu und verwandelt Stäbe in Sens. Die Ernte kann beginnen!",
		it = "Aggiunge diversi tipi di lame da mischia alle personalizzazioni delle armi, trasformando i bastoni in falci. Inizia la mietitura!",
		ja = "武器カスタマイズに複数の近接武器の刃を追加し、スタッフを鎌に変えます。収穫を始めましょう！",
		ko = "무기 커스터마이즈에 여러 종류의 근접 무기 칼날을 추가하여 스태프를 낫으로 변환합니다. 수확을 시작하세요!",
		pl = "Dodaje kilka rodzajów ostrzy do walki wręcz do personalizacji broni, przekształcając kostury w kosy. Niech żniwa się rozpoczną!",
		["pt-br"] = "Adiciona vários tipos de lâminas corpo a corpo às suas personalizações de armas, transformando cajados em foices. Que a colheita comece!",
		es = "Añade varios tipos de hojas de melé a tus personalizaciones de armas, transformando bastones en guadañas. ¡Que comience la cosecha!",
	},
	group_randomization = {
		en = "Randomization",
		ru = "Рандомизация",
		fr = "Randomisation",
		["zh-tw"] = "隨機化",
		["zh-cn"] = "随机化",
		de = "Randomisierung",
		it = "Randomizzazione",
		ja = "ランダム化",
		ko = "무작위화",
		pl = "Randomizacja",
		["pt-br"] = "Randomização",
		es = "Aleatorización",
	},
	mod_option_scythe_blades_randomization = {
		en = "Randomize Scythe Blades",
		ru = "Случайная настройка лезвий косы",
		fr = "Randomiser les lames de faux",
		["zh-tw"] = "隨機化鐮刀刀刃",
		["zh-cn"] = "随机化镰刀刀刃",
		de = "Sensenklingen randomisieren",
		it = "Randomizza le lame della falce",
		ja = "鎌の刃をランダム化",
		ko = "낫 칼날 무작위화",
		pl = "Losuj ostrza kosy",
		["pt-br"] = "Randomizar lâminas da foice",
		es = "Aleatorizar hojas de guadaña",
	},
	mod_option_scythe_blades_randomization_description = {
		en = "Allows randomized weapons to use scythe blades from this mod.",
		ru = "Позволяет использовать лезвия кос из этого мода в случайно сгенерированном оружии.",
		fr = "Permet aux armes aléatoires d'utiliser les lames de faux de ce mod.",
		["zh-tw"] = "允許隨機生成的武器使用此模組的鐮刀刀刃。",
		["zh-cn"] = "允许随机生成的武器使用本模组的镰刀刀刃。",
		de = "Ermöglicht es randomisierten Waffen, die Sensenklingen aus diesem Mod zu verwenden.",
		it = "Consente alle armi casuali di utilizzare le lame della falce di questa mod.",
		ja = "ランダム化された武器がこのMODの鎌の刃を使用できるようにします。",
		ko = "무작위화된 무기가 이 모드의 낫 칼날을 사용할 수 있도록 허용합니다.",
		pl = "Pozwala losowo generowanej broni używać ostrzy kosy z tego moda.",
		["pt-br"] = "Permite que armas aleatórias usem as lâminas da foice deste mod.",
		es = "Permite que las armas aleatorizadas utilicen las hojas de guadaña de este mod.",
	},
}